it("Sampleautodeposit", async function() {
	kony.automation.widget.touch(["frmAccountsLanding","customheader","topmenu","flxTransfersAndPay"], [159,23],null,null);
	kony.automation.widget.touch(["frmAccountsLanding"], null,null,[445,93]);
	kony.automation.flexcontainer.click(["frmAccountsLanding","customheader","topmenu","flxTransfersAndPay"]);
	kony.automation.widget.touch(["frmAccountsLanding"], null,null,[382,187]);
	kony.automation.flexcontainer.click(["frmAccountsLanding","customheader","topmenu","flxeTransfer"]);
	kony.automation.widget.touch(["frmeTransferSendMoney"], null,null,[966,318]);
	kony.automation.flexcontainer.click(["frmeTransferSendMoney","flxeTransferAutodeposit"]);
	kony.automation.widget.touch(["frmeTransferAutodeposit"], null,null,[1055,199]);
	kony.automation.button.click(["frmeTransferAutodeposit","btnAddNewRegistration"]);
	kony.automation.widget.touch(["frmeTransferRegisterAutodeposit"], null,null,[228,399]);
	kony.automation.flexcontainer.click(["frmeTransferRegisterAutodeposit","flxContactMethodChevron"]);
	kony.automation.widget.touch(["frmeTransferRegisterAutodeposit","flxSelectContactMethodSegment"], null,null,[58,19]);
	kony.automation.widget.touch(["frmeTransferRegisterAutodeposit"], null,null,[158,447]);
	kony.automation.flexcontainer.click(["frmeTransferRegisterAutodeposit","segContactMethod[0]","flxeTransferListBox"]);
	kony.automation.widget.touch(["frmeTransferRegisterAutodeposit"], null,null,[337,399]);
	kony.automation.textbox.enterText(["frmeTransferRegisterAutodeposit","tbxEmailAddress"],"rajagopalan.ganesan@temenos.com");
	kony.automation.widget.touch(["frmeTransferRegisterAutodeposit"], null,null,[268,442]);
	kony.automation.flexcontainer.click(["frmeTransferRegisterAutodeposit","flxSelectAccount"]);
	kony.automation.widget.touch(["frmeTransferRegisterAutodeposit","flxSelectAccountSegment"], null,null,[98,75]);
	kony.automation.widget.touch(["frmeTransferRegisterAutodeposit"], null,null,[193,543]);
	kony.automation.flexcontainer.click(["frmeTransferRegisterAutodeposit","segAccount[0,0]","flxAccountListItemWrapper"]);
	kony.automation.widget.touch(["frmeTransferRegisterAutodeposit"], null,null,[105,523]);
	kony.automation.flexcontainer.click(["frmeTransferRegisterAutodeposit","flxCheckBoxPubliclyAssociated"]);
	kony.automation.widget.touch(["frmeTransferRegisterAutodeposit"], null,null,[99,488]);
	kony.automation.flexcontainer.click(["frmeTransferRegisterAutodeposit","flxCheckBoxAcknowledgeAutodeposit"]);
	kony.automation.widget.touch(["frmeTransferRegisterAutodeposit"], null,null,[1107,527]);
	kony.automation.button.click(["frmeTransferRegisterAutodeposit","btnRegister"]);
	kony.automation.widget.touch(["frmeTransferRegisterAutodepositConfirm"], null,null,[1054,471]);
	kony.automation.button.click(["frmeTransferRegisterAutodepositConfirm","btnContinue"]);
});